export async function getOrder(id) {
  return (await getOrders()).find((order) => order.id.toString() === id)
}

export async function getRecentOrders() {
  return (await getOrders()).slice(0, 10)
}

export async function getOrders() {
  return [
    {
      id: 3000,
      url: '/orders/3000',
      date: 'May 9, 2024',
      patient: {
        name: 'Leslie Alexander',
        email: 'leslie.alexander@example.com',
        address: '123 Main St. Toronto, ON',
        country: 'Canada',
        countryFlagUrl: '/flags/ca.svg',
      },
      event: await getEvent('1000'),
    },
    {
      id: 3001,
      url: '/orders/3001',
      date: 'May 5, 2024',
      patient: {
        name: 'Michael Foster',
        email: 'michael.foster@example.com',
        address: '357 Bridge St. New York, NY',
        country: 'USA',
        countryFlagUrl: '/flags/us.svg',
      },
      event: await getEvent('1001'),
    },
    {
      id: 3002,
      url: '/orders/3002',
      date: 'Apr 28, 2024',
      patient: {
        name: 'Dries Vincent',
        email: 'dries.vincent@example.com',
        address: '456 Elm St. Vancouver, BC',
        country: 'Canada',
        countryFlagUrl: '/flags/ca.svg',
      },
      event: await getEvent('1002'),
    },
    {
      id: 3003,
      url: '/orders/3003',
      date: 'Apr 23, 2024',
      patient: {
        name: 'Lindsay Walton',
        email: 'lindsay.walton@example.com',
        address: '789 Oak St. Montreal, QC',
        country: 'Canada',
        countryFlagUrl: '/flags/ca.svg',
      },
      event: await getEvent('1000'),
    },
    {
      id: 3004,
      url: '/orders/3004',
      date: 'Apr 18, 2024',
      patient: {
        name: 'Courtney Henry',
        email: 'courtney.henry@example.com',
        address: '321 Pine St. Calgary, AB',
        country: 'Canada',
        countryFlagUrl: '/flags/ca.svg',
      },
      event: await getEvent('1003'),
    },
    {
      id: 3005,
      url: '/orders/3005',
      date: 'Apr 14, 2024',
      patient: {
        name: 'Tom Cook',
        email: 'tom.cook@example.com',
        address: '741 Lake St. Miami, FL',
        country: 'USA',
        countryFlagUrl: '/flags/us.svg',
      },
      event: await getEvent('1001'),
    },
    {
      id: 3006,
      url: '/orders/3006',
      date: 'Apr 10, 2024',
      patient: {
        name: 'Whitney Francis',
        email: 'whitney.francis@example.com',
        address: '654 Maple St. Ottawa, ON',
        country: 'Canada',
        countryFlagUrl: '/flags/ca.svg',
      },
      event: await getEvent('1002'),
    },
    {
      id: 3007,
      url: '/orders/3007',
      date: 'Apr 6, 2024',
      patient: {
        name: 'Leonard Krasner',
        email: 'leonard.krasner@example.com',
        address: '987 Birch St. Winnipeg, MB',
        country: 'Canada',
        countryFlagUrl: '/flags/ca.svg',
      },
      event: await getEvent('1000'),
    },
    {
      id: 3008,
      url: '/orders/3008',
      date: 'Apr 3, 2024',
      patient: {
        name: 'Floyd Miles',
        email: 'floyd.miles@example.com',
        address: '147 Cedar St. Quebec City, QC',
        country: 'Canada',
        countryFlagUrl: '/flags/ca.svg',
      },
      event: await getEvent('1000'),
    },
    {
      id: 3009,
      url: '/orders/3009',
      date: 'Mar 29, 2024',
      patient: {
        name: 'Emily Selman',
        email: 'emily.selman@example.com',
        address: '258 Willow St. Halifax, NS',
        country: 'Canada',
        countryFlagUrl: '/flags/ca.svg',
      },
      event: await getEvent('1003'),
    },
    {
      id: 3010,
      url: '/orders/3010',
      date: 'Mar 25, 2024',
      patient: {
        name: 'Kristin Watson',
        email: 'kristin.watson@example.com',
        address: '369 Spruce St. Edmonton, AB',
        country: 'Canada',
        countryFlagUrl: '/flags/ca.svg',
      },
      event: await getEvent('1001'),
    },
    {
      id: 3011,
      url: '/orders/3011',
      date: 'Mar 21, 2024',
      patient: {
        name: 'Emma Dorsey',
        email: 'emma.dorsey@example.com',
        address: '159 Park St. Chicago, IL',
        country: 'USA',
        countryFlagUrl: '/flags/us.svg',
      },
      event: await getEvent('1000'),
    },
    {
      id: 3012,
      url: '/orders/3012',
      date: 'Mar 16, 2024',
      patient: {
        name: 'Alicia Bell',
        email: 'alicia.bell@example.com',
        address: '741 Laurel St. Regina, SK',
        country: 'Canada',
        countryFlagUrl: '/flags/ca.svg',
      },
      event: await getEvent('1002'),
    },
    {
      id: 3013,
      url: '/orders/3013',
      date: 'Mar 12, 2024',
      patient: {
        name: 'Jenny Wilson',
        email: 'jenny.wilson@example.com',
        address: '852 Ash St. Saskatoon, SK',
        country: 'Canada',
        countryFlagUrl: '/flags/ca.svg',
      },
      event: await getEvent('1001'),
    },
    {
      id: 3014,
      url: '/orders/3014',
      date: 'Mar 8, 2024',
      patient: {
        name: 'Anna Roberts',
        email: 'anna.roberts@example.com',
        address: '852 Hill St. Houston, TX',
        country: 'USA',
        countryFlagUrl: '/flags/us.svg',
      },
      event: await getEvent('1002'),
    },
    {
      id: 3015,
      url: '/orders/3015',
      date: 'Mar 4, 2024',
      patient: {
        name: 'Benjamin Russel',
        email: 'benjamin.russel@example.com',
        address: '963 Cherry St. Victoria, BC',
        country: 'Canada',
        countryFlagUrl: '/flags/ca.svg',
      },
      event: await getEvent('1002'),
    },
    {
      id: 3016,
      url: '/orders/3016',
      date: 'Feb 28, 2024',
      patient: {
        name: 'Jeffrey Webb',
        email: 'jeffrey.webb@example.com',
        address: '654 Ocean St. Hamilton, ON',
        country: 'Canada',
        countryFlagUrl: '/flags/ca.svg',
      },
      event: await getEvent('1000'),
    },
    {
      id: 3017,
      url: '/orders/3017',
      date: 'Feb 23, 2024',
      patient: {
        name: 'Kathryn Murphy',
        email: 'kathryn.murphy@example.com',
        address: '357 River St. London, ON',
        country: 'Canada',
        countryFlagUrl: '/flags/ca.svg',
      },
      event: await getEvent('1000'),
    },
    {
      id: 3018,
      url: '/orders/3018',
      date: 'Feb 19, 2024',
      patient: {
        name: 'Lawrence Hunter',
        email: 'lawrence.hunter@example.com',
        address: '159 Lake St. Mississauga, ON',
        country: 'Canada',
        countryFlagUrl: '/flags/ca.svg',
      },
      event: await getEvent('1003'),
    },
    {
      id: 3019,
      url: '/orders/3019',
      date: 'Feb 15, 2024',
      patient: {
        name: 'Yvette Armstrong',
        email: 'yvette.armstrong@example.com',
        address: '852 Forest St. Markham, ON',
        country: 'Canada',
        countryFlagUrl: '/flags/ca.svg',
      },
      event: await getEvent('1003'),
    },
    {
      id: 3020,
      url: '/orders/3020',
      date: 'Feb 10, 2024',
      patient: {
        name: 'Angela Fisher',
        email: 'angela.fisher@example.com',
        address: '741 Hill St. Brampton, ON',
        country: 'Canada',
        countryFlagUrl: '/flags/ca.svg',
      },
      event: await getEvent('1001'),
    },
    {
      id: 3021,
      url: '/orders/3021',
      date: 'Feb 5, 2024',
      patient: {
        name: 'Blake Reid',
        email: 'blake.reid@example.com',
        address: '369 Valley St. Oshawa, ON',
        country: 'Canada',
        countryFlagUrl: '/flags/ca.svg',
      },
      event: await getEvent('1000'),
    },
    {
      id: 3022,
      url: '/orders/3022',
      date: 'Feb 1, 2024',
      patient: {
        name: 'Hector Gibbons',
        email: 'hector.gibbons@example.com',
        address: '258 Ridge St. Richmond Hill, ON',
        country: 'Canada',
        countryFlagUrl: '/flags/ca.svg',
      },
      event: await getEvent('1003'),
    },
    {
      id: 3023,
      url: '/orders/3023',
      date: 'Jan 27, 2024',
      patient: {
        name: 'Fabricio Mendes',
        email: 'fabricio.mendes@example.com',
        address: '147 Park St. Vaughan, ON',
        country: 'Canada',
        countryFlagUrl: '/flags/ca.svg',
      },
      event: await getEvent('1003'),
    },
    {
      id: 3024,
      url: '/orders/3024',
      date: 'Jan 22, 2024',
      patient: {
        name: 'Jillian Steward',
        email: 'jillian.steward@example.com',
        address: '987 Grove St. Windsor, ON',
        country: 'Canada',
        countryFlagUrl: '/flags/ca.svg',
      },
      event: await getEvent('1003'),
    },
    {
      id: 3025,
      url: '/orders/3025',
      date: 'Jan 18, 2024',
      patient: {
        name: 'Chelsea Hagon',
        email: 'chelsea.hagon@example.com',
        address: '654 Court St. Los Angeles, CA',
        country: 'USA',
        countryFlagUrl: '/flags/us.svg',
      },
      event: await getEvent('1003'),
    },
  ]
}

export async function getEvent(id) {
  return (await getEvents()).find((event) => event.id.toString() === id)
}

export async function getEventOrders(id) {
  return (await getOrders()).filter((order) => order.event.id.toString() === id)
}

export async function getEvents() {
  return [
    {
      id: 1000,
      name: 'Ozempic',
      url: '/events/1000',
      summary:
        'A once-weekly injection administered under the skin in the abdomen, thigh, or upper arm. Primarily prescribed for managing type 2 diabetes but also aids in weight loss. It’s used in adults with a BMI of 27 or higher who have weight-related health conditions or a BMI of 30 or higher.',
    },
    {
      id: 1001,
      name: 'Wegovy',
      url: '/events/1001',
      summary:
        "A once-weekly injection that is administered under the skin in the abdomen, thigh, or upper arm. It's usually prescribed for people with a BMI of 30 or higher (obese) or 27 or higher (overweight) with at least one weight-related condition",
    },
    {
      id: 1002,
      name: 'Mounjaro',
      url: '/events/1002',
      summary:
        'A once-weekly injection administered under the skin, typically prescribed for managing type 2 diabetes. It targets two hormone pathways, helping regulate blood sugar and promoting weight loss. Often prescribed off-label for weight loss in adults with obesity or overweight who have weight-related health conditions.',
    },
    {
      id: 1003,
      name: 'Zepbound',
      url: '/events/1003',
      summary:
        'A once-weekly injection administered under the skin, designed specifically for weight management. Approved for adults with a BMI of 30 or higher or a BMI of 27 or higher with weight-related conditions, targeting two hormonal pathways to enhance weight loss effectiveness.',
    },
  ]
}

export function getCountries() {
  return [
    {
      name: 'United Kingdom',
      code: 'GB',
      flagUrl: '/flags/gb.svg',
      regions: ['England', 'Scotland', 'Wales', 'Northern Ireland'],
    },
    {
      name: 'Canada',
      code: 'CA',
      flagUrl: '/flags/ca.svg',
      regions: [
        'Alberta',
        'British Columbia',
        'Manitoba',
        'New Brunswick',
        'Newfoundland and Labrador',
        'Northwest Territories',
        'Nova Scotia',
        'Nunavut',
        'Ontario',
        'Prince Edward Island',
        'Quebec',
        'Saskatchewan',
        'Yukon',
      ],
    },
    {
      name: 'Mexico',
      code: 'MX',
      flagUrl: '/flags/mx.svg',
      regions: [
        'Aguascalientes',
        'Baja California',
        'Baja California Sur',
        'Campeche',
        'Chiapas',
        'Chihuahua',
        'Ciudad de Mexico',
        'Coahuila',
        'Colima',
        'Durango',
        'Guanajuato',
        'Guerrero',
        'Hidalgo',
        'Jalisco',
        'Mexico State',
        'Michoacán',
        'Morelos',
        'Nayarit',
        'Nuevo León',
        'Oaxaca',
        'Puebla',
        'Querétaro',
        'Quintana Roo',
        'San Luis Potosí',
        'Sinaloa',
        'Sonora',
        'Tabasco',
        'Tamaulipas',
        'Tlaxcala',
        'Veracruz',
        'Yucatán',
        'Zacatecas',
      ],
    },
    {
      name: 'United States',
      code: 'US',
      flagUrl: '/flags/us.svg',
      regions: [
        'Alabama',
        'Alaska',
        'American Samoa',
        'Arizona',
        'Arkansas',
        'California',
        'Colorado',
        'Connecticut',
        'Delaware',
        'Washington DC',
        'Micronesia',
        'Florida',
        'Georgia',
        'Guam',
        'Hawaii',
        'Idaho',
        'Illinois',
        'Indiana',
        'Iowa',
        'Kansas',
        'Kentucky',
        'Louisiana',
        'Maine',
        'Marshall Islands',
        'Maryland',
        'Massachusetts',
        'Michigan',
        'Minnesota',
        'Mississippi',
        'Missouri',
        'Montana',
        'Nebraska',
        'Nevada',
        'New Hampshire',
        'New Jersey',
        'New Mexico',
        'New York',
        'North Carolina',
        'North Dakota',
        'Northern Mariana Islands',
        'Ohio',
        'Oklahoma',
        'Oregon',
        'Palau',
        'Pennsylvania',
        'Puerto Rico',
        'Rhode Island',
        'South Carolina',
        'South Dakota',
        'Tennessee',
        'Texas',
        'Utah',
        'Vermont',
        'U.S. Virgin Islands',
        'Virginia',
        'Washington',
        'West Virginia',
        'Wisconsin',
        'Wyoming',
        'Armed Forces Americas',
        'Armed Forces Europe',
        'Armed Forces Pacific',
      ],
    },
  ]
}
